add validation and testing in devops branch

diff --git a/.github/workflows/docker-pipeline.yml b/.github/workflows/docker-pipeline.yml
--- a/.github/workflows/docker-pipeline.yml
+++ b/.github/workflows/docker-pipeline.yml
@@ -17,3 +17,16 @@ jobs:
         
       - name: Test Image
         run: docker run -d -p 8080:80 nginx:alpine
+
+      # Validation and Testing
+      - name: Wait for container to start
+        run: sleep 5 # Container ko fully start hone ke liye 5 seconds dena
+
+      - name: Validate App on Port 8080
+        run: |
+          if curl -s -f http://localhost:8080 > /dev/null; then
+            echo "Success: Docker container is live and responding on port 8080!"
+          else
+            echo "Error: Docker container failed to respond."
+            exit 1 # Yeh pipeline ko Fail kar dega agar website na chali
+          fi
