add verification step to kubernetes branch

diff --git a/.github/workflows/k8s-pipeline.yml b/.github/workflows/k8s-pipeline.yml
--- a/.github/workflows/k8s-pipeline.yml
+++ b/.github/workflows/k8s-pipeline.yml
@@ -25,3 +25,19 @@ jobs:
           kubectl apply -f kubernetes/
           sleep 10
           kubectl get pods
+
+      - name: Validate Kubernetes Deployment and Test Port
+        run: |
+          # Background mein port-forward run karna (& ka nishaan background ke liye hai)
+          kubectl port-forward svc/ecommerce-service 8081:80 &
+          
+          # Pods ko traffic ready karne ke liye 10 seconds dena
+          sleep 10 
+          
+          # Curl ke zariye test karna
+          if curl -s -f http://localhost:8081 > /dev/null; then
+            echo "Success: K8s Application is live and responding on port 8081!"
+          else
+            echo "Error: K8s Application failed to respond."
+            exit 1
+          fi
